In [16]:
#AND gate implementation
import numpy as np
import tensorflow as tf

#example input 4 samples 2 featured each
X = tf.constant([[0,0],[0,1],[1,0],[1,1]],dtype = tf.float32)

In [92]:
#manually define weights and bias
W = tf.constant([[2],[2]],dtype = tf.float32) #[[W-F1],[W-F2]]
b = tf.constant([-3],dtype = tf.float32)

In [93]:
#forward pass: z = XW +b
z = tf.matmul(X,W) + b

In [94]:
#act (step func / sigmoid)
y_step = tf.cast(z >=0, tf.int32) # hard thresh(binary output)
y_sigmoid = tf.math.sigmoid(z) # soft prob

In [95]:
print("i/p: \n",X.numpy())
print("linear comb: \n",z.numpy())
print("step o/p perceptron: \n", y_step.numpy())
print("sig o/p: \n",y_sigmoid.numpy())

i/p: 
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
linear comb: 
 [[-3.]
 [-1.]
 [-1.]
 [ 1.]]
step o/p perceptron: 
 [[0]
 [0]
 [0]
 [1]]
sig o/p: 
 [[0.04742588]
 [0.26894143]
 [0.26894143]
 [0.7310586 ]]
