In [2]:
import numpy as np

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [4]:
print("Tensor A:\n",A)
print("Tensor A:\n",B)

Tensor A:
 [[1 2]
 [3 4]]
Tensor A:
 [[5 6]
 [7 8]]


In [5]:
#basic operations
add_res = A + B
sub_res = A - B
mul_res = A * B
div_res = A / B
matmul_res = A @ B
print("\n Add: ",add_res)
print("\n sub: ",sub_res)
print("\n mul: ",mul_res)
print("\n div: ",div_res)
print("\n manual: ",matmul_res)



 Add:  [[ 6  8]
 [10 12]]

 sub:  [[-4 -4]
 [-4 -4]]

 mul:  [[ 5 12]
 [21 32]]

 div:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]

 manual:  [[19 22]
 [43 50]]


In [6]:
import tensorflow as tf

A = tf.constant([[1,2],[3,4]],dtype = tf.float32)
B = tf.constant([[1,2],[3,4]],dtype = tf.float32)

In [7]:
#baSIC OPERATIONS

In [8]:
add_res = tf.add(A,B)
sub_res = tf.subtract(A,B)
mul_res = tf.multiply(A,B)
div_res = tf.divide(A,B)
matmul_res = tf.matmul(A,B)

In [11]:
print("add_res",add_res.numpy())
print("sub_res",sub_res.numpy())
print("mul_res",mul_res.numpy())
print("div_res",div_res.numpy())
print("matmul_res",matmul_res.numpy())

add_res [[2. 4.]
 [6. 8.]]
sub_res [[0. 0.]
 [0. 0.]]
mul_res [[ 1.  4.]
 [ 9. 16.]]
div_res [[1. 1.]
 [1. 1.]]
matmul_res [[ 7. 10.]
 [15. 22.]]


In [12]:
print("add_res",add_res)
print("sub_res",sub_res)
print("mul_res",mul_res)
print("div_res",div_res)
print("matmul_res",matmul_res)

add_res tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
sub_res tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
mul_res tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
div_res tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
matmul_res tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)


In [14]:
C = tf.constant([[1,2],[3,4]])
D = tf.constant([[1,2],[3,4]])

In [17]:
C.dtype

tf.int32