In [17]:
import numpy as np

In [18]:
data = np.arange(1,17).reshape(4,4)
print("Original tensor\n",data)

Original tensor
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [35]:
#split into 2 parts along columns
splits = np.split(data,4,axis=1)
print("\n Split parts: ")
for part in splits:
    print(part)


 Split parts: 
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 4]
 [ 8]
 [12]
 [16]]


In [26]:
#merge back into original tensor
merged = np.concatenate(splits)
print("Merged: \n",merged)

Merged: 
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [27]:
#statitics
mean_val = np.mean(data)
max_val = np.max(data)
min_val = np.min(data)
sum_val = np.sum(data)
std_val = np.std(data)

In [28]:
print("Mean: ",mean_val)
print("Max: ",max_val)
print("min: ",min_val)
print("sum: ",sum_val)
print("std: ",std_val)

Mean:  8.5
Max:  16
min:  1
sum:  136
std:  4.6097722286464435


In [41]:
import tensorflow as tf

data = tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype = tf.float32)

In [42]:
print("Original",data.numpy())

Original [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [44]:
splits = tf.split(data,num_or_size_splits=2,axis=1)
print(splits)

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 5.,  6.],
       [ 9., 10.]], dtype=float32)>, <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 3.,  4.],
       [ 7.,  8.],
       [11., 12.]], dtype=float32)>]


In [45]:
print("split parts")
for part in splits:
    print(part.numpy)

split parts
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 5.,  6.],
       [ 9., 10.]], dtype=float32)>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 3.,  4.],
       [ 7.,  8.],
       [11., 12.]], dtype=float32)>>


In [49]:
merged = tf.concat(splits,axis = 1)
print(merged.numpy())

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [52]:
#statitics
mean_val = tf.reduce_mean(data)
max_val = tf.reduce_max(data)
min_val = tf.reduce_min(data)
sum_val = tf.reduce_sum(data)
std_val = tf.math.reduce_std(data)

In [53]:
print("Mean: ",mean_val)
print("Max: ",max_val)
print("min: ",min_val)
print("sum: ",sum_val)
print("std: ",std_val)

Mean:  tf.Tensor(6.5, shape=(), dtype=float32)
Max:  tf.Tensor(12.0, shape=(), dtype=float32)
min:  tf.Tensor(1.0, shape=(), dtype=float32)
sum:  tf.Tensor(78.0, shape=(), dtype=float32)
std:  tf.Tensor(3.4520526, shape=(), dtype=float32)
